# Use the official Python image as the base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Install Java, wget, and SSL dependencies
RUN apt-get update && apt-get install -y --no-install-recommends default-jre libreoffice-java-common wget ca-certificates openssl apt-transport-https  unoconv fontconfig software-properties-common libxinerama1 ibus 
COPY LibreOffice_7.6.4_Linux_x86-64_deb.tar.gz .
# COPY libssl3_3.0.2-0ubuntu1.12_amd64.deb .
RUN tar -xvzf LibreOffice_7.6.4_Linux_x86-64_deb.tar.gz
#RUN dpkg -i /app/libssl3_3.0.2-0ubuntu1.12_amd64.deb
RUN dpkg -i /app/LibreOffice_*/DEBS/*.deb
RUN apt-get update
RUN ls /opt/
# #Configuring SOFFICE client for terminal operations
RUN ln -s /opt/libreoffice7.6/program/soffice /usr/local/bin/soffice
RUN ln -s /opt/libreoffice7.6/program/soffice /usr/local/bin/lowriter

RUN /opt/libreoffice7.6/program/soffice --version
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Create a new directory called "uploads"
RUN mkdir /app/uploads

#RUN echo "deb http://deb.debian.org/debian/ bookworm contrib" >> /etc/apt/sources.list
#RUN echo "deb-src http://deb.debian.org/debian/ bookworm contrib" >> /etc/apt/sources.list

#RUN apt-get update && apt-get install -y --no-install-recommends -t bookworm ttf-mscorefonts-installer 

RUN rm -Rf /usr/share/fonts/*
RUN ls -ltr /usr/share/fonts
COPY /fonts/* /usr/share/fonts
RUN ls -ltr /usr/share/fonts
RUN fc-cache -f -v
RUN fc-list

# RUN wget -O find_uno.py --no-check-certificate https://gist.githubusercontent.com/regebro/036da022dc7d5241a0ee97efdf1458eb/raw/find_uno.py
# RUN python3 find_uno.py
COPY ./shared /app/shared
COPY ./SAKeys/fe-key.json key.json
# Copy the application code to the container
COPY app.py .

# Expose port 5000 for the Flask application
EXPOSE 5000

# Run app.py when the container launches
CMD ["gunicorn", "-w", "1", "--worker-connections", "1", "-b", "0.0.0.0:5000","--timeout", "180", "app:app"]