# Use the official Python image as the base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Install Java, wget, and SSL dependencies
RUN apt-get update && apt-get install -y --no-install-recommends default-jre wget ca-certificates openssl apt-transport-https
# Download the Tika app JAR from Apache Hub
RUN wget -O ./tika-app.jar --no-check-certificate https://downloads.apache.org/tika/3.0.0-BETA/tika-app-3.0.0-BETA.jar
# Install the required Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./shared /app/shared

# Copy the application code to the container
COPY app-tika.py .

# Create a new directory called "uploads"
RUN mkdir /app/uploads

# Expose port 5000 for the Flask application
EXPOSE 5001

# Set the entrypoint command to run the Flask application
CMD ["python3", "app-tika.py"]