apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor
  template:
    metadata:
      labels:
        app: extractor
    spec:
      containers:
      - name: extractor
        image: extractor.azurecr.io/extractor:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-tika-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-tika-server
  template:
    metadata:
      labels:
        app: extractor-tika-server
    spec:
      containers:
      - name: extractor-tika-server
        image: extractor.azurecr.io/extractor-tika-server-ca:latest
        ports:
        - containerPort: 9998
